//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest.FilmData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilmContract", Namespace="http://schemas.datacontract.org/2004/07/TestService.DataContract")]
    [System.SerializableAttribute()]
    public partial class FilmContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DirectorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceTest.FilmData.GenreContract[] GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DirectorId {
            get {
                return this.DirectorIdField;
            }
            set {
                if ((this.DirectorIdField.Equals(value) != true)) {
                    this.DirectorIdField = value;
                    this.RaisePropertyChanged("DirectorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTest.FilmData.GenreContract[] Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName {
            get {
                return this.PhotoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoNameField, value) != true)) {
                    this.PhotoNameField = value;
                    this.RaisePropertyChanged("PhotoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenreContract", Namespace="http://schemas.datacontract.org/2004/07/TestService.DataContract")]
    [System.SerializableAttribute()]
    public partial class GenreContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenreName {
            get {
                return this.GenreNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreNameField, value) != true)) {
                    this.GenreNameField = value;
                    this.RaisePropertyChanged("GenreName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FilmData.ITestFilmData")]
    public interface ITestFilmData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/CheckConnection", ReplyAction="http://tempuri.org/ITestFilmData/CheckConnectionResponse")]
        string CheckConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/CheckConnection", ReplyAction="http://tempuri.org/ITestFilmData/CheckConnectionResponse")]
        System.Threading.Tasks.Task<string> CheckConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/GetFilms", ReplyAction="http://tempuri.org/ITestFilmData/GetFilmsResponse")]
        ServiceTest.FilmData.FilmContract[] GetFilms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/GetFilms", ReplyAction="http://tempuri.org/ITestFilmData/GetFilmsResponse")]
        System.Threading.Tasks.Task<ServiceTest.FilmData.FilmContract[]> GetFilmsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/AddFilm", ReplyAction="http://tempuri.org/ITestFilmData/AddFilmResponse")]
        void AddFilm(ServiceTest.FilmData.FilmContract film);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/AddFilm", ReplyAction="http://tempuri.org/ITestFilmData/AddFilmResponse")]
        System.Threading.Tasks.Task AddFilmAsync(ServiceTest.FilmData.FilmContract film);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/DeleteFilm", ReplyAction="http://tempuri.org/ITestFilmData/DeleteFilmResponse")]
        void DeleteFilm(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/DeleteFilm", ReplyAction="http://tempuri.org/ITestFilmData/DeleteFilmResponse")]
        System.Threading.Tasks.Task DeleteFilmAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/GetFilmById", ReplyAction="http://tempuri.org/ITestFilmData/GetFilmByIdResponse")]
        ServiceTest.FilmData.FilmContract GetFilmById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/GetFilmById", ReplyAction="http://tempuri.org/ITestFilmData/GetFilmByIdResponse")]
        System.Threading.Tasks.Task<ServiceTest.FilmData.FilmContract> GetFilmByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/GetGenres", ReplyAction="http://tempuri.org/ITestFilmData/GetGenresResponse")]
        ServiceTest.FilmData.GenreContract[] GetGenres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/GetGenres", ReplyAction="http://tempuri.org/ITestFilmData/GetGenresResponse")]
        System.Threading.Tasks.Task<ServiceTest.FilmData.GenreContract[]> GetGenresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/UpdateFilm", ReplyAction="http://tempuri.org/ITestFilmData/UpdateFilmResponse")]
        void UpdateFilm(ServiceTest.FilmData.FilmContract film);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestFilmData/UpdateFilm", ReplyAction="http://tempuri.org/ITestFilmData/UpdateFilmResponse")]
        System.Threading.Tasks.Task UpdateFilmAsync(ServiceTest.FilmData.FilmContract film);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestFilmDataChannel : ServiceTest.FilmData.ITestFilmData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestFilmDataClient : System.ServiceModel.ClientBase<ServiceTest.FilmData.ITestFilmData>, ServiceTest.FilmData.ITestFilmData {
        
        public TestFilmDataClient() {
        }
        
        public TestFilmDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestFilmDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestFilmDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestFilmDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckConnection() {
            return base.Channel.CheckConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckConnectionAsync() {
            return base.Channel.CheckConnectionAsync();
        }
        
        public ServiceTest.FilmData.FilmContract[] GetFilms() {
            return base.Channel.GetFilms();
        }
        
        public System.Threading.Tasks.Task<ServiceTest.FilmData.FilmContract[]> GetFilmsAsync() {
            return base.Channel.GetFilmsAsync();
        }
        
        public void AddFilm(ServiceTest.FilmData.FilmContract film) {
            base.Channel.AddFilm(film);
        }
        
        public System.Threading.Tasks.Task AddFilmAsync(ServiceTest.FilmData.FilmContract film) {
            return base.Channel.AddFilmAsync(film);
        }
        
        public void DeleteFilm(int id) {
            base.Channel.DeleteFilm(id);
        }
        
        public System.Threading.Tasks.Task DeleteFilmAsync(int id) {
            return base.Channel.DeleteFilmAsync(id);
        }
        
        public ServiceTest.FilmData.FilmContract GetFilmById(int id) {
            return base.Channel.GetFilmById(id);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.FilmData.FilmContract> GetFilmByIdAsync(int id) {
            return base.Channel.GetFilmByIdAsync(id);
        }
        
        public ServiceTest.FilmData.GenreContract[] GetGenres() {
            return base.Channel.GetGenres();
        }
        
        public System.Threading.Tasks.Task<ServiceTest.FilmData.GenreContract[]> GetGenresAsync() {
            return base.Channel.GetGenresAsync();
        }
        
        public void UpdateFilm(ServiceTest.FilmData.FilmContract film) {
            base.Channel.UpdateFilm(film);
        }
        
        public System.Threading.Tasks.Task UpdateFilmAsync(ServiceTest.FilmData.FilmContract film) {
            return base.Channel.UpdateFilmAsync(film);
        }
    }
}
